/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vlrgtvesuybqypbddhvk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZscmd0dmVzdXlicXlwYmRkaHZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNjMzMDgsImV4cCI6MjA4OTkzOTMwOH0.8Uo15oRhQHns6G4zJli5aGJGHZegjr-cv-lhHEtrCBQ"